# Lets see if it fix the problem
title: Hailin's New Journey
author: Luffy
email: hailin.du91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello Everyone! This is Hailin, and his journey!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
