# Lets see if it fix the problem
title: Luffy's New Journey
author: Hailin
email: hailin.du91@gmail.com
description: > # this means to ignore newlines until "baseurl:"

# social links
github_username: https://github.com/hailin-du

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
