# Lets see if it fix the problem
title: New World Not Showing
author: Luffy
email: hellohailindu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello New World! The Fifth King!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
